server:
  port: 8081
spring:
  application:
    name: MultiTenant
  datasource:
    url: 'jdbc:postgresql://localhost:5432/test?ApplicationName=MultiTenant'
    username: 'postgres'
    password: 'postgres'
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: none
logging:
  level:
    root: ERROR
    org.springframework.web: ERROR
    com.howtodoinjava: DEBUG
    org.hibernate: ERROR
    com:
      ms: TRACE
      
api:
  codify:
    secret: CODIFY-SOS-SECRET
    time: 6000000
    uri: /api
          